command:
  [
    "opentelemetry-instrument",
    "uvicorn",
    "server.app:combined_app",
    "--host",
    "0.0.0.0",
    "--port",
    "8000",
  ]

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_UC_FUNCTIONS_CATALOG
    value: "workspace"
  - name: DATABRICKS_UC_FUNCTIONS_SCHEMA
    value: "demo"
  - name: OTEL_TRACES_SAMPLER
    value: "always_on"
